### ISSUE TITLE
v0.1.18: Can't build exemple on windows

### ISSUE THREAD

**Issue by poka-IT** [physia/kflutter#11]
On new version 0.1.18, I can't build exemple on windows anymore:

```
Launching lib\main.dart on Windows in debug mode...
Nuget.exe not found, trying to download or use cached version.
C:\Users\poka\dev\kflutter\kplayer\kplayer\example\build\windows\packages\Microsoft.Windows.ImplementationLibrary\include\wil/cppwinrt.h(82,75): error C2338: Please include wil/cppwinrt.h before including any C++/WinRT headers [C:\Users\poka\dev\kflutter\kplayer\kplayer\example\build\windows\plugins\audioplayers_windows\audioplayers_windows_plugin.vcxproj]
C:\Users\poka\dev\kflutter\kplayer\kplayer\example\build\windows\packages\Microsoft.Windows.ImplementationLibrary\include\wil/cppwinrt.h(101,75): error C2338: C++/WinRT external catch clause already defined outside of WIL [C:\Users\poka\dev\kflutter\kplayer\kplayer\example\build\windows\plugins\audioplayers_windows\audioplayers_windows_plugin.vcxproj]
C:\Users\poka\dev\kflutter\kplayer\kplayer\example\build\windows\packages\Microsoft.Windows.ImplementationLibrary\include\wil/cppwinrt.h(82,75): error C2338: Please include wil/cppwinrt.h before including any C++/WinRT headers [C:\Users\poka\dev\kflutter\kplayer\kplayer\example\build\windows\plugins\audioplayers_windows\audioplayers_windows_plugin.vcxproj]
C:\Users\poka\dev\kflutter\kplayer\kplayer\example\build\windows\packages\Microsoft.Windows.ImplementationLibrary\include\wil/cppwinrt.h(101,75): error C2338: C++/WinRT external catch clause already defined outside of WIL [C:\Users\poka\dev\kflutter\kplayer\kplayer\example\build\windows\plugins\audioplayers_windows\audioplayers_windows_plugin.vcxproj]
2
C:\Users\poka\dev\kflutter\kplayer\kplayer\example\windows\flutter\ephemeral\.plugin_symlinks\dart_vlc\dartvlc\internal/events.h(68,11): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\Users\poka\dev\kflutter\kplayer\kplayer\example\build\windows\dart_vlc_core\dart_vlc_core.vcxproj]
```

I worked with version 0.1.11, so probably due to your change from just_audio to audioplayers.

**Comment by mohamadlounnas** [comment]
the main kplayer packege still use **just_audio** and **dart_vlc**
are u useing **kplayer_with_audioplayers**?

**Comment by mohamadlounnas** [comment]
can u try audioplayers alone?
there is file for example [audioplayers_test.dart](https://github.com/physia/kflutter/blob/main/kplayer/kplayer/example/lib/audioplayers_test.dart) uncommented and try use only audioplayers,
to see if the problem by the audioplayers packege

there is some solution may work, run:
```
flutter clean
flutter pub get
```
then delete windows folder, vscode should recreated  again when select windows
also visual studio may need repair, just open visual studio  installer and select repair

**Comment by poka-IT** [comment]
I tried clean, get, delete and recreate windows folder, same problem.
And same problem with audioplayer exemple package, so the problem is from them.

**Comment by poka-IT** [comment]
Ok sorry I just understood your answer, the problem came from my VSCode installation.
